GET http://127.0.0.1:8000/polls/
Accept: application/json

###
POST http://127.0.0.1:8000/polls/
Content-Type: application/json
Authorization: Token 96836753d98b228f3f71f88102695be9097c777c

{
  "title": "test poll3",
  "start_date": "2020-05-06T19:00:00",
  "end_date": "2021-05-05T19:00:00"
}

###
PUT http://127.0.0.1:8000/polls/3/
Content-Type: application/json
Authorization: Token 96836753d98b228f3f71f88102695be9097c777c

{
"title": "test poll33",
"start_date": "2021-05-06T18:00:00",
"end_date": "2022-05-06T18:00:00"
}


###
GET http://127.0.0.1:8000/polls/3/
Accept: application/json


###
DELETE http://127.0.0.1:8000/polls/1/
Authorization: Token 96836753d98b228f3f71f88102695be9097c777c


###
GET http://127.0.0.1:8000/questions/
Accept: application/json


###
POST http://127.0.0.1:8000/questions/
Content-Type: application/json
Authorization: Token 96836753d98b228f3f71f88102695be9097c777c

{
  "poll": 1,
  "text": "multiple_variant_question",
  "question_type": "multiple"
}

###
GET http://127.0.0.1:8000/questions/1/
Accept: application/json

###
GET http://127.0.0.1:8000/variants/
Accept: application/json

###
POST http://127.0.0.1:8000/variants/
Content-Type: application/json
Authorization: Token 96836753d98b228f3f71f88102695be9097c777c

{
  "question": 3,
  "text": "variant 4"
}


###
POST http://localhost:8000/auth/token/login/
Content-Type: application/json

{
"username":"admin",
"password":"admin"
}


###
POST http://localhost:8000/answers/
Content-Type: application/json

{
  "poll": 1,
  "participant_id": 10000,
  "answers": [
    {
      "question": 1,
      "text": "test"
    },
    {
      "question": 2,
      "variants": [2]
    },
    {
      "question": 3,
      "answer_variant": null,
      "variants": [5,6]
    }
  ]
}

###
GET http://127.0.0.1:8000/answers/10000/
Accept: application/json

