GET http://127.0.0.1:8000/polls/
Accept: application/json

###
POST http://127.0.0.1:8000/polls/
Content-Type: application/json
Authorization: Token afb5b921154ac4d161f0a7b905e4e9e4e7c2f9fc

{
  "title": "test poll",
  "start_date": "2021-05-06T19:00:00",
  "end_date": "2022-05-06T19:00:00"
}


###
GET http://127.0.0.1:8000/polls/2/
Accept: application/json


###
DELETE http://127.0.0.1:8000/polls/1/
Authorization: Token afb5b921154ac4d161f0a7b905e4e9e4e7c2f9fc


###
GET http://127.0.0.1:8000/questions/
Accept: application/json


###
POST http://127.0.0.1:8000/questions/
Content-Type: application/json
Authorization: Token afb5b921154ac4d161f0a7b905e4e9e4e7c2f9fc

{
  "poll": 2,
  "text": "multiple_variant_question",
  "question_type": "multiple"
}

###
GET http://127.0.0.1:8000/questions/1/
Accept: application/json


###
POST http://127.0.0.1:8000/questions/
Content-Type: application/json
Authorization: Token 98fb6429b65eed4017af10b4bcadaa9d52c08d95

{
  "poll": 1,
  "text": "test 2",
  "question_type": 2
}

###
GET http://127.0.0.1:8000/variants/
Accept: application/json

###
POST http://127.0.0.1:8000/variants/
Content-Type: application/json
Authorization: Token afb5b921154ac4d161f0a7b905e4e9e4e7c2f9fc

{
  "question": 3,
  "text": "variant 4"
}


###
POST http://localhost:8000/auth/token/login/
Content-Type: application/json

{
"username":"admin",
"password":"admin"
}


###
POST http://localhost:8000/answers/
Content-Type: application/json

{
  "poll": 2,
  "participant_id": 10000,
  "answers": [
    {
      "question": 1,
      "text": "test"
    },
    {
      "question": 2,
      "variants": [3]
    },
    {
      "question": 3,
      "answer_variant": null,
      "variants": [7,8]
    }
  ]
}

###
GET http://127.0.0.1:8000/answers/10000/
Accept: application/json

